Now only one prompt, it will take to the workflow. Is it something that is possible or it's like, you know, overkill? Now it might be possible, Gopi. So only testing is required. The way, the approach, whatever we are exactly giving, it will definitely follow. Sure, sure, sure. Okay, I'll let maybe Dipesh pick on it properly. Maybe if you are okay, Deepa. Yeah, so I will look into this also, like making as a standalone like agent. I will try in this way also, Gopi. So this will be like a direct approach, I feel. So I will work on that. Okay, sure. Yeah, so that's upgraded. Cool.

Text file for each team. User can edit it. So one more thing, sorry, sorry to interrupt, I just wanted to confirm one thing. So last time I think we discussed, the Confluence page, you have created a text file and then only you have utilized it, right? No? How did you do that? Yeah, yeah, yeah. I have this copy. Actually it is blocking the particular file. So how did you do that? Like you some blocking it, isn't it? It's unable to fetch that Confluence. Okay, okay. Here you have added it, right? Is it? Okay, okay, okay. Fine, fine, understand. So what I was doing is, like I just created in a text file, whatever the Confluence data is there. This is manual actually, so that's what I wanted to, yeah, yeah. Okay, so you have converted that as a doc and okay.

should look like in general. Let's say there are two chances. They are creating altogether a new Terraform folder and table, or adding it to the existing Terraform folder or table, right? Yes, there are first initial decision was existing Terraform folder or file.

question based on this, the decision will change. If it is an existing Terraform folder or file, you don't need a lot of stuff. You just need a table definition as such, name, data type, nullability, and description. I think that's it, right? If you are creating an existing Terraform folder, you don't need much, much information. You guys with me? Yes, yeah. If it is a new one, all we need to define as such. There are a lot of nitty-gritties as such. Yeah, there is a template here. We need to understand, okay, this is an IAM, okay, this is IAM. Let's not go through IAM at the moment. We'll take our repository on it. So there is a template here, and yeah, of course, the project ID, dataset ID, these are all needs to be given by the user. What I'm foreseeing is, you know, with the YAML perspective, it will be a bit difficult to understand as such. And they might not give proper info as such. If we have a Google form or something, formulating what are all the attributes that is needed over here. For sure, when you are creating a new data set, you need a dataset ID. You can formulate that, right, in the forms, you can have first initially a button asking yes or no. If you are creating the existing one or the creating new other one. Maybe other person can help you to build this before you do this. But my point of view is, if building a YAML would be the criteria, it will be difficult, it will add one more additional difficulty as such.

I don't know whether you are able to get it or not. No, no, we are getting it okay. But so current approach, like you want it to use the existing one or shall we go with the new one? It should serve both the cases. Maybe in the YAML file that you are configuring, you should tell whether the user is creating new or old one. And keeping all the things in the YAML file, I'm not sure how easy it is because, let's say I'm showing one example as one of the project. See, I have a ton of tables here. I want to create all these tables at once. How will I do it? This could be one use case you guys can work upon. Right? This is a new table and there are probably all the information as such, code, domain, data type, description.

is you are not giving additional burden to the user to convert this into a YAML. Then he's coming here, copying it, and you have an option that you can keep everything in an Excel. You are taking Excel as an input or CSV as an input. It could be a lot more columns. It is not specific. If he is able to keep specific columns, it's fine, and the headers will be somewhat not same. Please note all these pointers and test it whether we can be a bit more robust actions. Understood this place? Yeah, but the only thing is that still that user has a manual effort to create that input file. You know what I mean? So like initially when we started working, so the idea is that from design document, we fetch that data.

Okay. And in the file itself, in the file here, there are some key things. These are static. This one you know. This one is static. These ones are static. This one, data set, 27 and 24 data set changes. And these ones, you need to understand, like you know, what all the access concepts is. Based on that, you need to formulate the inputs. And these ones are mandatory. And once all the tables have gone, partitions and ones... For every FTB table, so for example, line number 407, okay, I mean, and I'm just... Okay. For all these tables, the, if you scroll down, table section, so all these, this table, like this crypto key project ID location and KMS key ring. Yes. Don't wanna change it. Same, right, for every FTB table. For not every FTB, no. For each project, it will be different. You mean project meaning? Project meaning, ID5, ID7. Not, not a Google project. You see this GID BRD, it's like, you know, only for our BRD project ID7. If some IDT7 is doing, they have to create their own KMS keys and key rings and come here. And this is static. These two are static. The KMS project ID and KMS location is static. Key and key ring will change. Okay. The point of time will need...


Yeah, we can do that, sir. Multiple and single we can convert, yes. Right, right, that is also true. I think, yeah, one sample we can do. Hey Dipesh, sorry, I don't know, like, it suddenly stopped, disconnected. Uh-huh, okay, okay. So I would say that also audit is not clear. What is the source? Mm-hmm, okay. So what do you think, like,
